FROM public.ecr.aws/lambda/nodejs:12
COPY package.json package-lock.json ${LAMBDA_TASK_ROOT}/
RUN npm ci --production
COPY . /${LAMBDA_TASK_ROOT}

# Add env variables
ENV DB_USERNAME $DB_USERNAME
ENV DB_PASSWORD $DB_PASSWORD
ENV RDS_HOST $RDS_HOST
ENV AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY
ENV AWS_DEFAULT_REGION $AWS_DEFAULT_REGION

CMD [ "app.handler" ]