name: AWS Lambda Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write
  pull-requests: read
  id-token: write

jobs:
  update_lambda:
    runs-on: ubuntu-latest
    env:
      ECR_IMAGE_TAG: latest
      AWS_DEFAULT_REGION: us-east-1
      AWS_LAMBDA_FUNC_NAME: btl-stats-lambda
      AWS_ECR_REPOSITORY_NAME: btl-stats

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/BTL-Github-Actions

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Am I logged in to ECR?
        id: test-login-ecr
        run: aws sts get-caller-identity

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          registry: ${{ steps.login-ecr.outputs.registry }}
          image_name: ${{ env.AWS_ECR_REPOSITORY_NAME }}
          session: "${{ env.AWS_SESSION_TOKEN }}"
          build_extra_args: >-
            --build-arg DB_USERNAME=${{ secrets.DB_USERNAME }}
            --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            --build-arg RDS_HOST=${{ secrets.RDS_HOST }}
          push_image_and_stages: true
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
          --function-name ${{ env.AWS_LAMBDA_FUNC_NAME }} \
          --image-uri "${{ secrets.AWS_ECR_IMAGE_URI }}:${{ env.ECR_IMAGE_TAG }}"
